import Head from "next/head";
import Image from "next/image";

export default function ToS() {
  return (
    <>
      <Head>
        <title>DeckThemes | ToS</title>
      </Head>
      <main className="flex w-full flex-grow flex-col items-center justify-center gap-4">
        <style>{`
        
        strong {
            font-size: 2em;
        }
        h2 {
            padding-top: 30px;
        }
        p {
            padding-top: 10px;
            padding-bottom: 10px;
        }
        .tos-container ul {
            padding-left: 20px;
            list-style: disc;
        }        
        `}</style>
        <div className="tos-container relative flex w-full flex-col justify-center px-10 pt-10 text-black dark:text-zinc-300">
          <h1 className="text-3xl font-bold md:text-5xl">Deckthemes Terms Of Use</h1>

          <h2>
            <strong>Last updated: 20.03.2023</strong>
          </h2>

          <h2>
            <strong>Interpretation</strong>
          </h2>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the
            following conditions. The following definitions shall have the same meaning regardless
            of whether they appear in singular or in plural.
          </p>
          <h2>
            <strong>Copyright</strong>
          </h2>
          <p>
            Please note that the content displayed on our website is generated by its users, and as
            such, we cannot guarantee the accuracy, completeness, or authenticity of such content.
            We strive to moderate and monitor user-generated content to ensure compliance with our
            policies and guidelines, but we cannot be held responsible for any legal issues that may
            arise from such content. It is the sole responsibility of the user to ensure that any
            content they contribute to the website does not infringe upon the copyrights or other
            intellectual property rights of any third party.
          </p>
          <p>
            This Terms of Use is based on Clippsly Ltd&apos;s Terms and Conditions, and have been
            fully authorized and allowed by the Company.
          </p>
          <p>
            To clarify, we do not assume any legal liability for any copyright problems that may
            arise from user-generated content. Users who contribute content to our website do so at
            their own risk and assume all legal responsibility for any copyright infringements or
            other legal issues that may arise from such content.
          </p>
          <p>
            We strongly advise users to carefully review our terms and use, as well as our policies
            and guidelines regarding user-generated content, to ensure compliance with all legal
            requirements. Should you have any questions or concerns regarding copyright or other
            legal issues related to user-generated content on our website, please do not hesitate to
            contact us for further assistance.
          </p>
          <h2>
            <strong>Asset Review and Quality Control</strong>
          </h2>
          <p>
            We take asset review very seriously, as it is essential to maintain the legality and
            integrity of our website.
          </p>
          <p>
            Our team reviews all submitted music and visual assets for accuracy, originality, and
            technical quality, among other factors. If a submission does not meet our standards, we
            reserve the right to reject it or request revisions until it meets our requirements.
          </p>
          <p>
            Please note that our quality control measures are in place to ensure that all music
            published on our website is free of any copyright issues and is completely legal to be
            published. We encourage all content creators to review our quality control guidelines
            before submitting their music or visual assets to our platform to ensure that it meets
            our requirements.
          </p>
          <h2>
            <strong>
              Requirements for audio assets <em>(AudioLoader)</em>:
            </strong>
          </h2>
          <ul>
            <li>The audio is 100% instrumental and does not contains any lyrics</li>
            <li>
              The audio asset does not contain any audio asset not owned by the publisher, not
              licensed or uploaded without copyright owner permission.
            </li>
            <li>
              The audio asset <em>(background music)</em> may not be louder than 10dB.
            </li>
            <li>Make the music loop as seamlessly as possible.&nbsp;</li>
            <li>
              Make sure that you’ve saved your music as <em>menu_music.mp3</em> in your pack
              directory.
            </li>
            <li>Make sure that the asset have been properly tested before being submited.</li>
            <li>
              Make sure it work properly on the lastest beta and stable versions of SteamOS, Decky
              Loader, and AudioLoader
            </li>
          </ul>
          <h2>
            <strong>
              Requirements for visual assets <em>(CSSLoader &amp; AudioLoader)</em>:
            </strong>
          </h2>
          <ul>
            <li>
              Make sure that the art cover of the asset is not registered trademark or is not
              copyrighted by any 3rd party.
            </li>
            <li>
              This theme’s preview image does not include text unless it is necessary to describe
              changes that can be made.
            </li>
            <li>
              Make sure that theme is under 10MB in size and uses the least disk space possible.
            </li>
            <li>
              If this is a system-wide theme that also targets the keyboard, the keyboard theming is
              toggleable
            </li>
            <li>If this theme targets the keyboard, it applies to the default keyboard.</li>
            <li>
              Make sure that the asset have been fully tested and indicated as finished before
              submitting.
            </li>
            <li>
              Make sure that the visual asset does not contain any sexual or explicit content.
            </li>
            <li>
              This theme works properly on the latest beta and stable versions of SteamOS, Decky
              Loader and CSS Loader.
            </li>
            <li>This theme only uses * or !important if absolutely necessary.</li>
            <li>
              This theme does not bundle any other themes with it, and uses dependencies where
              necessary.
            </li>
            <li>This theme prefixes any CSS variables with a unique identifier.</li>
            <li>
              This theme&apos;s target has been marked appropriately and only styles said target.
            </li>
            <li>
              Make sure that you own or have permission from the copyright owner to use the art for
              the asset.
            </li>
          </ul>
          <p>
            If you have any questions or concerns about our quality control measures or guidelines,
            please do not hesitate to contact our team for assistance. We are committed to ensuring
            that our platform provides a fair and transparent publishing process for all our content
            providers.
          </p>
          <h2>
            <strong>Termination</strong>
          </h2>
          <p>
            <strong>Reasons that may lead to suspension of Your access:</strong>
          </p>
          <ul>
            <li>Submission of low quality submissions.</li>
            <li>Publishing inappropriate assets (eg. Gore, Pornography, Drugs).</li>
            <li>Publishing any assets not properly licensed or associated with Nintendo.</li>
            <li>Frequent errors in submissions (eg. .json file)</li>
          </ul>
          <p>
            We reserve the right to suspend your access to DeckThemes if you violate our terms of
            use or engage in inappropriate behavior.
          </p>
          <p>
            Please note that account suspension is not appealable and is up to Our own discretion.
            If your account is suspended, you will not be allowed to use any of our services, and
            any attempts to create new accounts will be immediately blocked.
          </p>
          <p>
            Upon termination, your right to use our services will cease immediately. We encourage
            you to review our terms of use carefully to ensure that you comply with all our rules
            and regulations. If you have any questions or concerns, please do not hesitate to
            contact our team for assistance.
          </p>
          <h2>
            <strong>Limitation of Liability</strong>
          </h2>
          <p>
            We are not liable whatsoever for any UGC (User Generated Content) potentially breaking
            the copyright law. We do not own any of the content that is being uploaded by the users
            of the site.
          </p>
          <p>
            Finally, please be aware that we are not responsible for any content posted by our
            users, and we cannot guarantee the accuracy or reliability of such content. Users are
            solely responsible for the content they post on our service, and we encourage our users
            to report any inappropriate or illegal content they encounter.
          </p>
          <h2>Contact Us</h2>
          <p>If you have any questions about these Terms and Conditions, You can contact us:</p>
          <ul className="!list-none !p-0 invert dark:invert-0">
            <li>
              <Image width={200} height={60} src="/contact_info.png" alt="Email Contact Info" />
            </li>
          </ul>
        </div>
      </main>
    </>
  );
}
